/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.bancaire;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author Silver
 */
public class Login extends javax.swing.JFrame {
Statement stm;
ResultSet rs, rs1;
String login;
String mdp;
Connecter con;
Connection conn=null;
PreparedStatement ps = null, ps1=null;
public static String t1;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conn = ConexionBD.Conexion();
    }
     public String utilisateur() {
        return t1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usr_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mdp_txt = new javax.swing.JTextField();
        connect_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Mot de passe");

        mdp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdp_txtActionPerformed(evt);
            }
        });

        connect_btn.setText("se connecter");
        connect_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connect_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usr_txt)
                        .addComponent(mdp_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mdp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(connect_btn)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mdp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdp_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdp_txtActionPerformed

    private void connect_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_btnActionPerformed
  
        String user= usr_txt.getText();
        String password=mdp_txt.getText();
        
//        requete="select * from user where Login= '"+user+"'";
        
//    try {
//        stm=con.obtenirconnexion().createStatement();
//        ResultSet rs1= stm.executeQuery(requete);
//        if(rs1.getString("Login").length() == 0){
//            JOptionPane.showMessageDialog(null, "introuvable");
//        }else{
//            if(rs1.getString("Mdp").equals(password)){
//                this.dispose();
//                MyApp a = new MyApp();
//                a.setVisible(true);  
//            }else{
//            JOptionPane.showMessageDialog(null, "mot de passe incorrect");
//            }
//        }
//    } catch (SQLException ex) {
//        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//    }
    
    
     
    String requete ="select * from user where Login = ? and Mdp =? ";
    String query="insert into current_user(Login) values ('"+user+"')";
        try{
            
            ps = conn.prepareStatement(requete);
            ps.setString(1, user);
            ps.setString(2, password);
            rs = ps.executeQuery();
        if(rs.next()){
             this.t1 = rs.getString("Login");
             
               
            
//          System.out.println(t1 ) ;  
//          JOptionPane.showMessageDialog(null, t1);
          dispose();
          new MyApp().setVisible(true);
                        
        }else{
        System.out.println("introuvable") ;
        }   
            
        }catch(Exception e){
            System.out.println("--> Exception : " + e) ;
           
        }
        
    
//    try{
//             stm=con.obtenirconnexion().createStatement();
//             ResultSet rs= stm.executeQuery(requete);
//            login= rs.getString("Login");
//            mdp=rs.getString("Mdp");
//            if(login.equals(user)&& mdp.equals(password)){
//        new MyApp().setVisible(true);
//      this.dispose();}else{JOptionPane.showMessageDialog(null, "erreur de connexion");}
//        }catch(SQLException | HeadlessException e){
//            System.out.print(e);
//        }
    }//GEN-LAST:event_connect_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mdp_txt;
    private javax.swing.JTextField usr_txt;
    // End of variables declaration//GEN-END:variables
}
